name:                PeanoZ
version:             0.1.0.0
github:              "laughinginloud/PeanoZ"
license:             GPLv3
author:              "Mattia Martelli"
maintainer:          "mattia.martelli@live.it"
copyright:           "2020 Mattia Martelli"

extra-source-files:
- README.md
- ChangeLog.md

description:         Progetto con l'estensione degli assiomi di Peano agli interi.

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  PeanoZ-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PeanoZ
