name:                Peano
version:             0.1.0.0
github:              "laughinginloud/Peano"
license:             GPLv3
author:              "Mattia Martelli"
maintainer:          "mattia.martelli@live.it"
copyright:           "2020 Mattia Martelli"

extra-source-files:
- README.md
- ChangeLog.md

description:         Progetto con varie estensioni degli assiomi di Peano.

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  Peano-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Peano
